baseurl: ""
url: https://www.kssim.com
enforce_ssl: www.kssim.com

theme_settings:
  favicon: assets/favicon.ico
  description: "KyeongSeob Sim"

  google_analytics: UA-116951375-2
  katex: true 
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"


markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: []
exclude: ["Gemfile", "Gemfile.lock", "*.gem", "LICENSE", "README.md"]
